name: JBKConsultant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70799
title: JBK Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6a0d0e'
    - '#000000'
    - '#545454'
    - '#7c7c7c'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
